//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoviesGenre
    {
        public int MoviesGenre_ID { get; set; }
        public int Movies_ID { get; set; }
        public int Genre_ID { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual Movy Movy { get; set; }
    }
}
