//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoviesRentalPrice
    {
        public int MoviesRentalPrice_ID { get; set; }
        public int Movies_ID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public System.DateTime createdDate { get; set; }
    
        public virtual Movy Movy { get; set; }
    }
}
