//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsersTransaction()
        {
            this.UsersRentals = new HashSet<UsersRental>();
        }
    
        public int UsersTransaction_ID { get; set; }
        public int Users_ID { get; set; }
        public string AuthCode { get; set; }
        public Nullable<bool> isShipped { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersRental> UsersRentals { get; set; }
    }
}
