//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersSession
    {
        public int UsersSession_ID { get; set; }
        public int Users_ID { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
